export const CAPTION_TAIL_PAD_SECONDS = 1 / 30;
export const DEFAULT_PAUSE_REMOVAL_MIN_GAP_SECONDS = 0.7;
export const PAUSE_REMOVAL_CUT_START_PADDING_SECONDS = 0.015;
export const PAUSE_REMOVAL_CUT_END_PADDING_SECONDS = 0.05;
export const TRANSCRIPT_CUT_AUDIO_SMOOTHING_SECONDS = 0.02;
export const TRANSCRIPT_CUT_AUDIO_OVERLAP_SECONDS = 0.018;
export const TRANSCRIPT_CUT_VISUAL_BOUNDARY_GUARD_SECONDS = 1 / 30;
