export const CAPTION_TAIL_PAD_SECONDS = 1 / 30;
export const DEFAULT_PAUSE_REMOVAL_MIN_GAP_SECONDS = 0.7;
export const MIN_PLAYABLE_TRANSCRIPT_GAP_SECONDS = 0.5;
export const PAUSE_REMOVAL_CUT_START_PADDING_SECONDS = 0.015;
export const PAUSE_REMOVAL_CUT_END_PADDING_SECONDS = 0.05;
export const TRANSCRIPT_MANUAL_CUT_RESUME_GUARD_SECONDS =
	PAUSE_REMOVAL_CUT_END_PADDING_SECONDS;
export const TRANSCRIPT_CUT_AUDIO_FADE_OUT_SECONDS = 0.008;
export const TRANSCRIPT_CUT_AUDIO_FADE_IN_SECONDS = 0.012;
export const TRANSCRIPT_CUT_AUDIO_SMOOTHING_SECONDS =
	TRANSCRIPT_CUT_AUDIO_FADE_IN_SECONDS;
export const TRANSCRIPT_CUT_AUDIO_OVERLAP_SECONDS = 0.012;
export const TRANSCRIPT_CUT_VISUAL_BOUNDARY_GUARD_SECONDS = 1 / 30;
